/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Chart: typeof import('./src/components/message/Chart/index.vue')['default']
    ChartText: typeof import('./src/components/message/ChartText.vue')['default']
    ChartTextArea: typeof import('./src/components/chartTextArea.vue')['default']
    ChatChart: typeof import('./src/components/message/Chart/ChatChart.vue')['default']
    ChatCode: typeof import('./src/components/message/ChatCode.vue')['default']
    ChatInput: typeof import('./src/components/chatInput.vue')['default']
    ChatList: typeof import('./src/components/chatList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeftAside: typeof import('./src/components/leftAside.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UsePinia: typeof import('./src/components/usePinia.vue')['default']
  }
}
